"""empty message

Revision ID: 0aad6d6d62fd
Revises: 986a4ba6fab6
Create Date: 2024-07-30 12:05:52.739642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aad6d6d62fd'
down_revision = '986a4ba6fab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('account_password', sa.String(), nullable=True))

    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accounts_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'accounts', ['accounts_id'], ['accounts_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('accounts_id')

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('account_password')
        batch_op.drop_column('account_email')

    # ### end Alembic commands ###
