"""empty message

Revision ID: 0ab12efbb188
Revises: 31cad41a2d24
Create Date: 2024-07-28 15:30:32.817229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ab12efbb188'
down_revision = '31cad41a2d24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sets',
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.Column('set_number', sa.Integer(), nullable=True),
    sa.Column('number_of_reps', sa.Integer(), nullable=True),
    sa.Column('weight_in_lbs', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.exercise_id'], ),
    sa.PrimaryKeyConstraint('set_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sets')
    # ### end Alembic commands ###
