"""empty message

Revision ID: 0da2ca594d84
Revises: 60b564a991bb
Create Date: 2024-07-28 14:03:00.059128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0da2ca594d84'
down_revision = '60b564a991bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Workout Date', sa.String(length=15), nullable=True),
    sa.Column('Workout Time of Day', sa.String(length=10), nullable=True),
    sa.Column('Type of Exercise', sa.String(length=100), nullable=True),
    sa.Column('Exercise Name', sa.String(length=50), nullable=True),
    sa.Column('Sets', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout')
    # ### end Alembic commands ###
