"""empty message

Revision ID: 1f4356476b46
Revises: 
Create Date: 2024-07-17 13:30:51.644384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f4356476b46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Exercise Name', sa.String(length=50), nullable=True),
    sa.Column('Sets', sa.Integer(), nullable=True),
    sa.Column('Reps', sa.Integer(), nullable=True),
    sa.Column('Weight', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout')
    # ### end Alembic commands ###
