"""empty message

Revision ID: 60b564a991bb
Revises: ec125413d6f0
Create Date: 2024-07-23 16:00:10.552546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60b564a991bb'
down_revision = 'ec125413d6f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Workout Time of Day', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.drop_column('Workout Time of Day')

    # ### end Alembic commands ###
