"""empty message

Revision ID: 77cc3c03181e
Revises: e3662e70b86c
Create Date: 2024-08-01 17:33:49.597587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77cc3c03181e'
down_revision = 'e3662e70b86c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('accounts_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=15), nullable=True),
    sa.Column('last_name', sa.String(length=25), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('account_email', sa.String(), nullable=True),
    sa.Column('account_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('accounts_id'),
    sa.UniqueConstraint('account_email')
    )
    op.create_table('workout',
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('accounts_id', sa.Integer(), nullable=True),
    sa.Column('Workout Date', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['accounts_id'], ['accounts.accounts_id'], ),
    sa.PrimaryKeyConstraint('workout_id')
    )
    op.create_table('exercises',
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=True),
    sa.Column('exercise_name', sa.String(length=50), nullable=True),
    sa.Column('number_of_sets', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.workout_id'], ),
    sa.PrimaryKeyConstraint('exercise_id')
    )
    op.create_table('sets',
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.Column('set_number', sa.Integer(), nullable=True),
    sa.Column('number_of_reps', sa.Integer(), nullable=True),
    sa.Column('weight_in_lbs', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.exercise_id'], ),
    sa.PrimaryKeyConstraint('set_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sets')
    op.drop_table('exercises')
    op.drop_table('workout')
    op.drop_table('accounts')
    # ### end Alembic commands ###
