"""empty message

Revision ID: 8f14e23fd497
Revises: 77cc3c03181e
Create Date: 2024-08-02 17:22:17.444880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f14e23fd497'
down_revision = '77cc3c03181e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_times',
    sa.Column('workout_time_of_day_id', sa.Integer(), nullable=False),
    sa.Column('workout_time_of_day', sa.String(length=10), nullable=False),
    sa.Column('time_of_day_description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('workout_time_of_day_id'),
    sa.UniqueConstraint('workout_time_of_day')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_times')
    # ### end Alembic commands ###
