"""empty message

Revision ID: b803deab5c6b
Revises: 6a0afc752b7e
Create Date: 2024-07-23 15:47:31.149008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b803deab5c6b'
down_revision = '6a0afc752b7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Workout Date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.drop_column('Workout Date')

    # ### end Alembic commands ###
