"""empty message

Revision ID: c6806ef7b7ef
Revises: 8dd1ffff6553
Create Date: 2024-08-07 13:52:57.201321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6806ef7b7ef'
down_revision = '8dd1ffff6553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('account_password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_password_hash', sa.VARCHAR(length=150), nullable=True))

    # ### end Alembic commands ###
