"""empty message

Revision ID: ceeafa257c00
Revises: 65e86ac177f4
Create Date: 2024-08-04 13:18:38.529185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceeafa257c00'
down_revision = '65e86ac177f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_accounts')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=25),
               nullable=False)
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('account_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('account_password',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercise_type_id', sa.Integer(), nullable=False))
        batch_op.alter_column('workout_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('exercise_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('number_of_sets',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'exercise_types', ['exercise_type_id'], ['exercise_type_id'])

    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.alter_column('exercise_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('set_number',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('number_of_reps',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('weight_in_lbs',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workout_time_of_day', sa.Integer(), nullable=False))
        batch_op.alter_column('accounts_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'workout_times', ['workout_time_of_day'], ['workout_time_of_day_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('accounts_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('workout_time_of_day')

    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.alter_column('weight_in_lbs',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('number_of_reps',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('set_number',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('exercise_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('number_of_sets',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('exercise_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('workout_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('exercise_type_id')

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.alter_column('account_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('account_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=25),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)

    op.create_table('_alembic_tmp_accounts',
    sa.Column('accounts_id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=15), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=25), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=False),
    sa.Column('account_email', sa.VARCHAR(), nullable=False),
    sa.Column('account_password', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('accounts_id'),
    sa.UniqueConstraint('account_email')
    )
    # ### end Alembic commands ###
