"""empty message

Revision ID: dd2368972cc7
Revises: 0da2ca594d84
Create Date: 2024-07-28 14:46:20.720285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd2368972cc7'
down_revision = '0da2ca594d84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout',
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('Workout Date', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('workout_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout')
    # ### end Alembic commands ###
