"""empty message

Revision ID: ec125413d6f0
Revises: b803deab5c6b
Create Date: 2024-07-23 15:54:51.298403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec125413d6f0'
down_revision = 'b803deab5c6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.alter_column('Workout Date',
               existing_type=sa.DATE(),
               type_=sa.String(length=15),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.alter_column('Workout Date',
               existing_type=sa.String(length=15),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
